### ISSUE TITLE
[Question] Force reset env after N steps/seconds

### ISSUE THREAD

**Issue by Karol-G** [DLR-RM/stable-baselines3#100]
Hi,

I have an environment that becomes buggy after a certain time. Sadly this cannot be fixed from my side. So it would be best if the environment could be reset after a certain number of steps or seconds. However, I don't want to simply reset the environment without the agent knowing it. So is there a way to tell the stabel-baselines framework to reset my env after a certain number of steps or seconds?

Best
Karol

**Comment by PartiallyTyped** [comment]
Well yes and no. You can wrap the environment in a timelimit wrapper from OpenAI’s gym library. Unfortunately you would have to notify the agent that the terminal state is due to the number of steps and not because it is terminal. You can do this by adding a time feature, we do this in stable baselines zoo.

**Comment by Karol-G** [comment]
Yeah. That is a good option. I did not think of this, thanks!

Best
Karol
