### ISSUE TITLE
[Question] Use VecTransposeImage for frame observations?

### ISSUE THREAD

**Issue by Karol-G** [DLR-RM/stable-baselines3#103]
Hi,

I have a custom env with frame observations:

```
class MyEnv(gym.Env):
    def __init__(self):
        self.observation_space = spaces.Box(low=0, high=255, shape=(40, 40, 1), dtype=np.uint8)
        ....
    .....
```

The documentation states that I should wrap my custom env with `VecTransposeImage`.
Should it look like this in the end (with Monitor)?

```
env = gym.make(env)
env = VecTransposeImage(env)
env = Monitor(env, log_dir)
model = model = DQN('CnnPolicy', env, learning_starts=learning_starts, verbose=1, tensorboard_log=tensorboard_log)
model.learn(total_timesteps)
```

Or is VecTransposeImage applied internally already if I use `CnnPolicy`?

Best,
Karol

**Comment by Miffyli** [comment]
> Or is VecTransposeImage applied internally already if I use CnnPolicy?

VecTransposeImage is automatically applied when code detects an image observation, and policies [also transpose](https://github.com/DLR-RM/stable-baselines3/blob/758b140b9de1761892d988ec65f595f5ba90b2f4/stable_baselines3/common/policies.py#L224) if needed. 

There might be bit of a bug here though: it seems that transposing is always done regardless of where the channels are placed, so that will break things up if somebody puts channels first in the environment.

**Comment by Karol-G** [comment]
Ok, Good to know. So if I understand it correctly: With shape=(40, 40, 1) with the cannel dim coming last, I am on the safe side?

Best,
Karol

**Comment by Miffyli** [comment]
Yup! With that the channel dim gets transposed to be the first axis.

**Comment by Karol-G** [comment]
Thanks for the quick reply!

Best,
Karol
