### ISSUE TITLE
Provide a example for `collect_rollouts` function

### ISSUE THREAD

**Issue by bdzjorg** [DLR-RM/stable-baselines3#1169]
### 📚 Documentation

I would like to use `collect_rollouts` function but there has no example that I can follow. 

Actually, I have tried to use `collect_rollouts` like this:
```python
import gym
from stable_baselines3 import SAC
from stable_baselines3.common.callbacks import ProgressBarCallback
from stable_baselines3.common.buffers import ReplayBuffer
from stable_baselines3.common.type_aliases import TrainFreq, TrainFrequencyUnit
from stable_baselines3.common.vec_env import DummyVecEnv

env = gym.make("HalfCheetah-v2")

vec_env = DummyVecEnv([lambda: gym.make("HalfCheetah-v2")])
callback = ProgressBarCallback
train_freq = TrainFreq(2, TrainFrequencyUnit.EPISODE)
buffer = ReplayBuffer(buffer_size=2*10**3, observation_space=env.observation_space, action_space=env.action_space)

model = SAC.load("./logs/sac/HalfCheetah-v2_1/best_model")
model.set_parameters("./logs/sac/HalfCheetah-v2_1/best_model")
vec_env.reset()
model.collect_rollouts(vec_env, callback, train_freq, buffer)
```

Unfortunately, the following error happens:
```python
Traceback (most recent call last):
  File "rollout_data.py", line 23, in <module>
    model.collect_rollouts(vec_env, callback, train_freq, buffer)
  File "/Users/bytedance/.pyenv/versions/env3813/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 577, in collect_rollouts
    callback.on_rollout_start()
TypeError: on_rollout_start() missing 1 required positional argument: 'self'
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

**Comment by araffin** [comment]
Hello,
`collect_rollout` is not really part of the public API, that's why it is not currently documented.
However, you can find a concrete example here:  https://github.com/yuanmingqi/rl-exploration-baselines

If you take a look at the code, you need to call `setup_learn()` and setup the callback before:
https://github.com/DLR-RM/stable-baselines3/blob/5ef10c8e69b52e1376e6c2c636737d6dd528dda1/stable_baselines3/common/off_policy_algorithm.py#L323-L355

> I would like to use collect_rollouts function but there has no example that I can follow.

what is your use case?

Side note: `model.set_parameters("./logs/sac/HalfCheetah-v2_1/best_model")` is not needed normally.
