### ISSUE TITLE
Slow learning/Disabling logging?

### ISSUE THREAD

**Issue by eliegoudout** [DLR-RM/stable-baselines3#1212]
### ❓ Question

Hello,

I'm not sure why, but when I do `model.learn(...)`, learning becomes really slow after about 50k learning steps. I suspect that the logger is causing this. If so, is there any way to disable logging altogether? I tried using `model.set_logger(None)` but of course it doesn't seem to be the way to go. I couldn't find any mention of "logger disabling" in the docs.

Thanks!

**Comment by qgallouedec** [comment]
What make you think that it is due the logger?
What environment/algo do you use?

**Comment by eliegoudout** [comment]
Thanks for your answer.

I use a `DQN` model and a custom environment.
I first thought about the replay_buffer, but I tried to use `buffer_size=0` and it didn't change anything. So I thought about the logger.
I though mayber it would make sense if after a certain number of steps the logs were longer to access because it might be stored in a different way after a certain size.

**Comment by qgallouedec** [comment]
> I use a `DQN` model and a custom environment.

DQN starts with a first phase of interaction collection before starting the learning. This phase is usually quite fast because it does not require any update of the agent. Then the learning starts (by default after 50k timesteps). It is therefore normal that the fps decreases at this stage.

> I tried to use `buffer_size=0` 
 
Don't do that. The algorithm would crash, or the agent will not learn. DQN is off-policy, so it requires a reasonable buffer size.

> So I thought about the logger. I though mayber it would make sense if after a certain number of steps the logs were longer to access because it might be stored in a different way after a certain size.

I understand, but that's not how it works. The time spent logging is minimal. As I explained above, learning does not slow down, but starts at 50k. It takes that long to process the collected interaction.

If your observations are images, then I highly recommend using cuda. How many fps do you drop to after 50k time steps?

**Comment by eliegoudout** [comment]
Oh ok, it mâles sense then, thank you. Where could I find reference to this 50k hardcoded parameter in thé docs please?

I don't use images but i do drop from 6.5k/s to 300/s.

I will look into cuda setting for sure, it was on my todo list!

Thanks again :)

**Comment by qgallouedec** [comment]
Look at [the DQN parameters](https://stable-baselines3.readthedocs.io/en/master/modules/dqn.html#parameters), `learning_starts`.

> I don't use images but i do drop from 6.5k/s to 300/s.

These are quite normal values. Look for [example on CartPole](https://wandb.ai/openrlbenchmark/sb3/reports/time-fps-22-12-13-22-46-55---VmlldzozMTQ0MTY0), you get the same order of magnitude (here, the `learning_starts` is set to 1k).

**Comment by eliegoudout** [comment]
Ok!
Thank you Very much!
