### ISSUE TITLE
Entropy log-prob estimation

### ISSUE THREAD

**Issue by AndyShih12** [DLR-RM/stable-baselines3#127]
I think this line should be negated, since entropy_loss should store the negated entropy.

https://github.com/DLR-RM/stable-baselines3/blob/bd2aae0c27d238a6a2c2f3a4c54066dfb30bd49b/stable_baselines3/ppo/ppo.py#L201

**Comment by araffin** [comment]
Hello,
nice catch ;)

In fact, we have a test for that: 

https://github.com/DLR-RM/stable-baselines3/blob/bd2aae0c27d238a6a2c2f3a4c54066dfb30bd49b/tests/test_distributions.py#L89

We would appreciate a PR that solve that issue ;) (for A2C too)

**Comment by Leo-xh** [comment]
I guess there is a misunderstanding, we mean that in
https://github.com/DLR-RM/stable-baselines3/blob/bd2aae0c27d238a6a2c2f3a4c54066dfb30bd49b/stable_baselines3/ppo/ppo.py#L207
this loss is designed to maximize the entropy of the policy in the meanwhile, so the entropy should be *subtract* from the policy loss and the value function loss
the following 2 lines are right because it computes the *negative entropy*
https://github.com/DLR-RM/stable-baselines3/blob/bd2aae0c27d238a6a2c2f3a4c54066dfb30bd49b/stable_baselines3/ppo/ppo.py#L202-L203
but the following 2 lines computes the *entropy*
https://github.com/DLR-RM/stable-baselines3/blob/bd2aae0c27d238a6a2c2f3a4c54066dfb30bd49b/stable_baselines3/ppo/ppo.py#L199-L201

**Comment by Miffyli** [comment]
Yup, we understood it this way from the original post. A PR to fix this issue would welcome, along with similar fix for A2C :)
