### ISSUE TITLE
[Question] Is there any relationship between n_steps and max_episode_steps?

### ISSUE THREAD

**Issue by tfederico** [DLR-RM/stable-baselines3#1272]
### ❓ Question

Is there any relationship between `n_steps` for algorithms (like PPO) and `max_episode_steps` defined when registering a custom env? What happens if `n_steps` > `max_episode_steps`?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
- `max_episode_steps` is the maximum number of times you can interact with your environment before it returns the `done` signal. At this point, you can't interact with it anymore, you have to reset it (by calling `env.reset()`). This has nothing to do with the learning algorithm.
- `n_steps` is the number of times the (on-policy) algorithm interacts with the environment between two policy updates (i.e. the internal weight update). 
- It is ok to have `n_steps` > `max_episode_steps` because the algorithm resets the environment (thus starts a new episode) whenever necessary. Note that the algorithm does not reset the environment after a policy update. It continues to interact from where it was before the update.

**Comment by araffin** [comment]
some (minor) additional remarks:

> At this point, you can't interact with it anymore, you have to reset it (by calling env.reset()). This has nothing to do with the learning algorithm.

in practice, we do need to know when this happens because when an episode ends because of timeout, we need to treat it differently compared to other termination (this has to do with value bootstrapping), if you are using gym `max_episode_steps`/`TimeLimit` wrapper, you don't need to worry about it.

> Note that the algorithm does not reset the environment after a policy update. It continues to interact from where it was before the update.

and it uses its value function to bootstrap the return for the truncated episode (so to pretends it is not truncated).

**Comment by tfederico** [comment]
Thanks for the clarification!

So what would happen at training/evaluation time if the number of steps required to execute a task if greater than `max_episode_steps`?

**Comment by qgallouedec** [comment]
If the number of steps required to execute a task if greater than max_episode_steps, then the agent will fail to learn the task. The `max_episode_steps` must be chosen to allow an agent to solve the task.

Note that this matter is independent from SB3, and only related to your environment.
