### ISSUE TITLE
N_envs in custom gym environment 

### ISSUE THREAD

**Issue by chaubeyniha** [DLR-RM/stable-baselines3#1285]
### 🐛 Bug

I am using a custom environment which does not have n_envs.  Due to this issue in the environment, I am unable to use VecFrameStacking. As I have no created the custom environment, I cannot add n_envs =1 but I was wondering if there is way to work around this for VecFrameStacking.

### Code example

```python
import gym
import numpy as np
from gym import spaces

from stable_baselines3 import A2C
from stable_baselines3.common.env_checker import check_env


class CustomEnv(gym.Env):

    def __init__(self):
        super().__init__()
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(14,))
        self.action_space = spaces.Box(low=-1, high=1, shape=(6,))

    def reset(self):
        return self.observation_space.sample()

    def step(self, action):
        obs = self.observation_space.sample()
        reward = 1.0
        done = False
        info = {}
        return obs, reward, done, info

env = CustomEnv()
check_env(env)

model = A2C("MlpPolicy", env, verbose=1).learn(1000)
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
You give us very little information, and it's hard to understand what your problem is. As a general answer, the way to use the environment vectorization is the same for custom and non-custom environments. You just have to use (cf [doc](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#multiprocessing-unleashing-the-power-of-vectorized-environments)):

```python
from stable_baselines3.common.vec_env import make_vec_env

class CustomEnv: ...

venv = make_vec_env(CustomEnv, n_envs=2)
```

And if you want to use the VecFrameStack, just wrap it like this:

```python
from stable_baselines3.common.vec_env import VecFrameStack

venv = VecFrameStack(venv, n_stack=4)
```

**Comment by chaubeyniha** [comment]
The problem is rather that n_envs doesnt exist in the custom environment I am using. As I havent created it I cannot change this. Because n_envs does not exist using VecFrameStack as you stated:
venv = VecFrameStack(venv, n_stack=4)

Gives me the error: venv.n_envs does not exist. So I was wondering if there was a way to work around this.

**Comment by qgallouedec** [comment]
`VecFrameStack` is a vectorized wrapper, so you've to use it with a vectorized environment. If you instantiate the environment as I explained in my previous comment (with `make_vec_env`), you shouldn't encounter this error anymore. 
If the error remains, I invite you to fill in the issue template completely, because it's really hard to provide a solution with the little information you give.
