### ISSUE TITLE
[Question] why doesn't SB3 allow custom observation preprocessing?

### ISSUE THREAD

**Issue by ArchieGertsman** [DLR-RM/stable-baselines3#1333]
### ❓ Question

In the `extract_features` method of the `BaseModel` class, observations are preprocessed using `preprocessing.preprocess_obs` prior to being fed into the feature extractor. This preprocessing function does not support general spaces, so it would be convenient to directly pass the observation into a custom feature extractor, e.g. if the observation space is `Graph` and the feature extractor contains a GNN. Preprocessing could then include converting the graph observation to a PyG `Data` object. This question is related to #1280, but I am more generally wondering why SB3 doesn't allow more customization (though I appreciate how much it already allows).

I am copying components of SB3's PPO implementation in my own project that uses graph observations, and it appears that everything about it is compatible with GNN's, so long as observation preprocessing and observation batching (i.e. collation) could be customized. I would love to use SB3 directly, but I'm hitting seemingly subtle roadblocks. Maybe I'm fundamentally misunderstanding SB3, and this level of customizability is infeasible to provide.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> r, e.g. if the observation space is Graph and the feature extractor contains a GNN. 

as noted in https://github.com/DLR-RM/stable-baselines3/issues/1280, SB3 doesn't officially support GNN (or only with Box space) and graph space.

> This preprocessing function does not support general spaces,

SB3 preprocessing is meant to work out of the box in the vast majority of cases.
When you need more customization/flexibility, best is to actually have custom classes/fork SB3 (which is what you are doing) because changes in pre-processing probably requires changes somewhere else.

We don't offer full customization usually to limit the complexity of the code (for instance, we recently removed shared network for PPO to simplify the code, which allow easier customization when defining custom policy).

> I am copying components of SB3's PPO implementation in my own project that uses graph observations, and it appears that everything about it is compatible with GNN's,

Could you please link your code in #1280? (we will probably add it to our doc)

Also, if you have a way in mind to over custom pre-processing without complexifying the code too much, we can also discuss that solution (and maybe open a draft PR to see how it looks concretely).
