### ISSUE TITLE
Abstract method to obtain action probability distribution

### ISSUE THREAD

**Issue by npit** [DLR-RM/stable-baselines3#1347]
### ❓ Question

Is there a general (i.e. model-agnostic) way to obtain the probability distribution over a discrete action space?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

Partial duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1257, https://github.com/DLR-RM/stable-baselines3/issues/568 and 

There is no common method because the algorithms handle things differently under the hood, however, the two issues showcase how to do it for the two type of algorithms that supports discrete action (PPO-like / DQN-like).

**Comment by npit** [comment]
Thanks.
Indeed, it appears you can get the action probs for an input observation `obs` like below.
```
ppo_like_probs = model.policy.get_distribution(obs).probs
dqn_like_probs = torch.softmax(model.policy.q_net(obs), dim=1)
```
