### ISSUE TITLE
[Question] Action Scaling PPO

### ISSUE THREAD

**Issue by danielstankw** [DLR-RM/stable-baselines3#1362]
### ❓ Question

Hi, 
I have opened related issue a while ago but after further analysis I got more questions.
https://github.com/DLR-RM/stable-baselines3/issues/1293

I am using PPO to learn control parameters of my controller. Based on the tutorial videos provided by @araffin I understand that the best way to set bounds of the action space is by normalizing them i.e. setting bounds as [-1, 1] and then recalling them in the environment if needed.
+=1 std from the mean contains 68% of the data, so if I set the bounds to -1 and 1, I guess the remaining 32% will get squeezed at the limits, so then inside my env i can re-scale those values to whatever limits i want. 

**Question**
s<<0  if I set the action space to be ex. [-1000,1000], I understand that initial the action will be drawn from Gaussian of mean 0 and std=1, but with time when agent explores, and is given feedback in form of reward/ state will the mean and standard deviation change, if the desired action space is in the area of ex. [-500,500] ? 

b) Assuming the answer to the above is yes,  how is the variance updated? Is it a NN that is being trained? 

Regards

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> will the mean and standard deviation change, if the desired action space is in the area of ex. [-500,500] ?

you mean if you set the action space limits to [-500, 500] instead of rescaling [-1, 1] inside your env?
Well, it might learn to output larger actions, but without entropy bonus, the std tends to shrink (so the actor becomes more deterministic and explores less over time), so my guess is that it might either not work or take much more time compared to simply rescaling the action inside the env.

For PPO, the variance is an independent variable being updated with the actor.
For SAC, the variance is an output of the actor, so it depends on the state and is also updated with the actor.

**Comment by danielstankw** [comment]
> you mean if you set the action space limits to [-500, 500] instead of re-scaling [-1, 1] inside your env?

I mean, to set the box boundaries (in my case its in gym wrapper) so that the action space sampled from Gausian inside PPO is clipped between [-500,500] instead of [-1,1], and then not using use re-scaling inside my env.
Up to my understanding, in that way agent will have a large exploration space and it might take a while to learn but it can find parameters that before I haven't even taken into account when scaling them in my custom env.

> For PPO, the variance is an independent variable being updated with the actor.

Any chance you could refer me to a part in the code that does the update of variance, so I can investigate further? 

I have set the bounds of my action space to [-1,1] (as recommended in the video) and then re-scaled them between [0,150] in my env. The issue I have is that the agent learned mostly parameters on the edges of the clipping i.e. -1,1->(after re-scaling)-> 0, 150. The matrix of parameters suppose to be positive definite, so it cant have diagonal zero/ negative terms, so scaling [0,150] didn't work as it learned that 0 on diagonal is good parameter, which it isn't.

**Comment by araffin** [comment]
> Any chance you could refer me to a part in the code that does the update of variance, so I can investigate further?

log std comes from 
https://github.com/DLR-RM/stable-baselines3/blob/085bdd5a68be7748e62ca710162f16ac7b62ddfc/stable_baselines3/common/policies.py#L551-L553
and
https://github.com/DLR-RM/stable-baselines3/blob/085bdd5a68be7748e62ca710162f16ac7b62ddfc/stable_baselines3/common/distributions.py#L150

The rest is done in the `train()` method of PPO using auto-diff.

>  The matrix of parameters suppose to be positive definite

I guess you will need to use matrix factorization to ensure that constrain by design.
As done in https://arxiv.org/abs/1907.04490
