### ISSUE TITLE
Problem with google colab 

### ISSUE THREAD

**Issue by chukalexander** [DLR-RM/stable-baselines3#1406]
There seems to be a problem installing the package to google colab, which was still working as of 21st-Mar-2023
Please advise

![image](https://user-images.githubusercontent.com/117527004/227237498-87a4336f-c265-4c6c-b73a-54f0b5cf9524.png)

**Comment by araffin** [comment]
Hello,
I think the colab still runs afterward, no?
The issue seems to be related to gym, probably related to https://github.com/DLR-RM/stable-baselines3/issues/1324 and https://github.com/openai/gym/issues/3176#issuecomment-1408598628

Should be solved by https://github.com/DLR-RM/stable-baselines3/pull/1327

**Comment by chukalexander** [comment]
The the module is not installed in the above case, and colab will not run.

#1327 solves the problem, thank you

**Comment by JY251** [comment]
I found this issue is caused by SB3 using gym version 0.21.0. When I tried to install this version using `!pip install gym==0.21.0` on Google Colab, it didn't work.
I then attempted to install other versions, such as the latest version and version `0.22.0`, and was succeeded in doing so with `pip install`.
There seems to be some code within the SB3 library that specifies the gym version, so I addressed this issue by changing them not to specify the gym version and was able to install SB3 by `!pip install git+https://github.com/JY251/stable-baselines3.git`.

This is my forked and modified repository of SB3:
[JY251/stable-baselines3](https://github.com/JY251/stable-baselines3/blob/master/docs/conda_env.yml).

**Comment by araffin** [comment]
> There seems to be some code within the SB3 library that specifies the gym version

yes, SB3 pins gym version as later version have some breaking changes.

If you want to use latest gym version or gymnasium, please take a look at https://github.com/DLR-RM/stable-baselines3/pull/1327.

> The the module is not installed in the above case, and colab will not run.

When I try to reproduce the error, setuptools fallback to legacy install and I can import the correct gym version afterward.

Doing install in verbose mode `!pip install gym==0.21 -vvv` show the real error:
```
 Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/wheel/vendored/packaging/requirements.py", line 35, in __init__
      parsed = parse_requirement(requirement_string)
    File "/usr/local/lib/python3.9/dist-packages/wheel/vendored/packaging/_parser.py", line 64, in parse_requirement
      return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
    File "/usr/local/lib/python3.9/dist-packages/wheel/vendored/packaging/_parser.py", line 82, in _parse_requirement
      url, specifier, marker = _parse_requirement_details(tokenizer)
    File "/usr/local/lib/python3.9/dist-packages/wheel/vendored/packaging/_parser.py", line 126, in _parse_requirement_details
      marker = _parse_requirement_marker(
    File "/usr/local/lib/python3.9/dist-packages/wheel/vendored/packaging/_parser.py", line 147, in _parse_requirement_marker
      tokenizer.raise_syntax_error(
    File "/usr/local/lib/python3.9/dist-packages/wheel/vendored/packaging/_tokenizer.py", line 163, in raise_syntax_error
      raise ParserSyntaxError(
  wheel.vendored.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
      opencv-python>=3.
```

**Comment by JiXiang-Zhou** [comment]
When I tried to install imitation package, I got the same error. How to fix that

**Comment by araffin** [comment]
> When I tried to install imitation package, I got the same error. How to fix that

Please read https://github.com/DLR-RM/stable-baselines3/issues/1406#issuecomment-1481317788
See https://github.com/openai/gym/issues/3200 for a solution
