### ISSUE TITLE
[Question] How does SB3 sample transitions in vectorized envs for off-policy algos

### ISSUE THREAD

**Issue by kbkartik** [DLR-RM/stable-baselines3#1649]
### ❓ Question

How is minibatch sampling for vectorized envs (consider sequential processing of envs) with off policy RL implemented in SB3? Let's say there are 5 envs. Every step the agent gets 5 transitions and pushes it to the buffer. While doing critic and policy updates, do we randomly sample transitions of batchsize N or do we randomly sample timesteps of batchsize N, thereby effectively giving us N*5 transitions?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
For each training sequence, the agent samples N transitions, taken uniformly from the collected dataset, regardless of the number of parallel environments.

To go into a little more detail, when given a batch size of N, the agent first samples N environment indices, then N timesteps indices. It then select the transitions according to these two indices.

**Comment by kbkartik** [comment]
How is the "done" variable taken care of for completion of an episode and doing env.reset()? In vec envs, do we just care about the number of experiences and save "done" variable only for Q(s', a') bootstrap? Where is env.reset executed when one the sub environments is complete and "done" is true?

**Comment by qgallouedec** [comment]
> How is the "done" variable taken care of for completion of an episode and doing env.reset()? In vec envs, do we just care about the number of experiences and save "done" variable only for Q(s', a') bootstrap? Where is env.reset executed when one the sub environments is complete and "done" is true?

For this, check the [Vectorized environments section of the doc](https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html).




> Also, how do we ensure that training and validation seeds are separate and don't overlap in vectorized envs? For single env, its easy to set seeds. How do we do those for vec envs?

Answer [here in the doc](https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html#stable_baselines3.common.vec_env.VecEnv.seed). Basically, when the environment is created, the first inner env gets `seed`, the second `seed+1`, the third `seed+2` and so on.

I assume that the validation seed refers to the evaluation env seed. You don't really need to define different seeds, because the actions taken by the agent during training are different from those in evaluation, so you can expect different trajectories. However, if you really need different seeds, you can define them at initialization:

```python
from stable_baselines3 import SAC
from stable_baselines3.common.callbacks import EvalCallback
from stable_baselines3.common.env_util import make_vec_env

env_id = "Pendulum-v1"
seed = 0

train_env = make_vec_env(env_id, n_envs=4, seed=0)
eval_env = make_vec_env(env_id, n_envs=2, seed=seed+10)

eval_callback = EvalCallback(eval_env, eval_freq=100)

model = SAC("MlpPolicy", train_env)
model.learn(5000, callback=eval_callback)
```
