### ISSUE TITLE
TypeError: reset() got an unexpected keyword argument 'seed'

### ISSUE THREAD

**Issue by KFM135** [DLR-RM/stable-baselines3#1725]
### 🐛 Bug

I am using PPO (from stable_baselines3) in a custom environment (gymnasium). I think the Monitor wrapper is not working for me. I get the following error:
```
  File "C:\Users\kzm0114\PycharmProjects\RL\problem_env_new_test1.py", line 400, in <module>
    model.learn(total_timesteps=int(timesteps), progress_bar=True)
  File "C:\Users\kzm0114\PycharmProjects\RL\venv\lib\site-packages\stable_baselines3\ppo\ppo.py", line 308, in learn
    return super().learn(
  File "C:\Users\kzm0114\PycharmProjects\RL\venv\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 246, in learn
    total_timesteps, callback = self._setup_learn(
  File "C:\Users\kzm0114\PycharmProjects\RL\venv\lib\site-packages\stable_baselines3\common\base_class.py", line 424, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
  File "C:\Users\kzm0114\PycharmProjects\RL\venv\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 76, in reset
    obs, self.reset_infos[env_idx] = self.envs[env_idx].reset(seed = self._seeds[env_idx])
  File "C:\Users\kzm0114\PycharmProjects\RL\venv\lib\site-packages\stable_baselines3\common\monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
TypeError: reset() got an unexpected keyword argument 'seed'
```
The PPO algorithm works fine in the gym environment without the monitor wrapper. If I try to use the following line `env = Monitor(env, log_dir)` in `gym` env, then I get the following error:
`  File "C:\Users\kzm0114\PycharmProjects\RL\venv\lib\site-packages\stable_baselines3\ppo\ppo.py", line 104, in __init__
    super().__init__(
  File "C:\Users\kzm0114\PycharmProjects\RL\venv\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 81, in __init__
    super().__init__(
  File "C:\Users\kzm0114\PycharmProjects\RL\venv\lib\site-packages\stable_baselines3\common\base_class.py", line 180, in __init__
    assert isinstance(self.action_space, supported_action_spaces), (
AssertionError: The algorithm only supports (<class 'gymnasium.spaces.box.Box'>, <class 'gymnasium.spaces.discrete.Discrete'>, <class 'gymnasium.spaces.multi_discrete.MultiDiscrete'>, <class 'gymnasium.spaces.multi_binary.MultiBinary'>) as action spaces but MultiDiscrete([129  62]) was provided`

I need the monitor wrapper to visualize the training results. I don't know what is wrong with where. I would greatly appreciate any help. Thanks.

### To Reproduce

```python
from stable_baselines3 import ...

```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by tty666** [comment]
That's not the only issue ...
with gymnasium you need seed now into your reset method declaration ...
Without gymnasium (so using the old gym "patch" ) you are asked for seed=data but also options=options now where before you could just declare reset(self) ...
Also ... the result of reset before was observation only where today you need to give observation and reset_info !
The same apply for the step method now :

    observation, reward, terminated, truncated, info = env.step(data) this "truncated" wasn't there before as well and I am pretty sure more and more I adapt the code (using simply None as I have no clue actually of what those new returned data or parameters are there for compared to before ) that I will find more of those changes ...
   
   I didn't found any new example or updated data about it into the documentation :
   
   https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html
   
   So please could we have more information about your last changes because it makes our applications totally useless currently ... or maybe we should go back to previous version to avoid this issue ?

**Comment by araffin** [comment]
> My issue does not relate to a custom gym environment. (Use the custom gym env template instead)

> I have provided a minimal and working example to reproduce the bug

Hello,
the minimum requirements for seeking help are not met, so it's hard to help you.

**Comment by tty666** [comment]
> > My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
> 
> > I have provided a minimal and working example to reproduce the bug
> 
> Hello, the minimum requirements for seeking help are not met, so it's hard to help you.

I agree the initial post is missing a lot of information but what about the information I shared, this about the basic structure for PPO models using stable_baselines3.
init, reset, step, next_observation
reset,step,next_observation got tweaked in a way they need more parameters in and deliver more parameters out.
Where was it mentioned ? Do we have a documentation about this somewhere to help the migration from 1.8 to 2.X ?
Thanks a lot for your help !

**Comment by araffin** [comment]
> reset,step,next_observation got tweaked in a way they need more parameters in and deliver more parameters out.
Where was it mentioned ? Do we have a documentation about this somewhere to help the migration from 1.8 to 2.X ?

The problem doesn't come from SB3 but from gym/gymnasium, you should check their migration guide.
We also updated our env checker to print meaningful error.

**Comment by tty666** [comment]
Yes you are totally right I found the information here :

https://gymnasium.farama.org/api/env/#gymnasium.Env.reset

This explains all the issues as in the latest gymnasium version (26) it becomes default and probably the "gym patch" also follow the same rules as it probably relies on gymnasium anyway ...

so we have to adapt the code to become compliant with gymnasium a simple sloution for step would be to do :

terminated=done
truncated=False
return obs,reward,terminated,truncated,info

if you don't use the truncated/terminated distinction ... and want to keep your code working with "done" everywhere else as before ...
For the reset it's a bit more tricky as we have to manage the entry of the method : seed + options (or we generate a seed and pass it through or we let the seed=None so it will take by itself from /dev/urandom) and the "options" is for me still very "abstract" I don't get how it's used not so much info in the documentation about it ...
Last part is to share "info" like we do with step for reset in the return of reset() methode but I don't see the interest in my case so it will be empty info ...

Hop it helps the initial ticket creator to understand the issue also.
I think you could close the case because his error is also not linked to SB3 but to Gymnasium 0.26...

**Comment by KFM135** [comment]
Thanks, @tty666 and @araffin.

**Comment by AbhayGoyal** [comment]
How did you solve this issue @KFM135
