### ISSUE TITLE
[Question] How was the evaluation environment seeded and reset before each evaluation?

### ISSUE THREAD

**Issue by kharitonov-ivan** [DLR-RM/stable-baselines3#1765]
### ❓ Question

Hi! Thanks for the library! I am confused about reproducible experiments and couldn't find how the seeds for environments are set in [evaluate_policy](https://github.com/DLR-RM/stable-baselines3/blob/e3dea4b2e03da6fb7ea70db89602909081a7967b/stable_baselines3/common/evaluation.py#L84C20-L84C23). I use this function as I use EvalCallback.

Maybe I am wrong, and it's not important. Are we expecting that when we perform evaluation, it is a deterministic process, meaning that the initial conditions of the environments from one eval procedure to another will be the same?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by cleversonahum** [comment]
Hello @araffin

I have a question about the seeds during different evaluation rounds. I have a custom environment in which the reward values and average reward vary a lot depending on the episodes. Also, I use the default random generator from the environment to generate some variables.  Even if I am able to set the seed to the environment before passing it to the EvalCallback, in the second evaluation round, I will obtain totally different values for the variables based on the Random Generator from the environment (even if using the same episodes from the first round). I am saving the best model to use afterward. Still, considering these conditions, each evaluation round seems to face different conditions due to random seeds being used, making the comparison to select the best model unfair. A flag to set the seed could be included in the EvalCallback to avoid this behavior when needed.

**Comment by araffin** [comment]
as I wrote, stochasticity in the evaluation should not be a problem as long as you do quantitative evaluation.
The `evaluate_policy` can also return the list of episodic return, so you can choose your own metric to select the best model (e.g. using median instead of mean).

The main issue with having a fully fixed evaluation setting is that you would tend to overfit to it (select the model that works best for that setting only).

**Comment by cleversonahum** [comment]
Thank you for getting back. I understand your point about stochasticity in the evaluation not being an issue for most environments, mainly if you can set many episodes to evaluate. But there are some exceptions. As I described before, I am considering 10 episodes for evaluation in my environment, and there is a great chance that the difficulty level faced by the first evaluation round will be very different from the second. Therefore, the agent performance comparison is not valid in these cases since one of them was evaluated in a much harder scenario. Moreover, here, "overfitting" is not a problem since the comparison between evaluation round performances doesn't make sense. I created a custom callback that sets the seed every time the evaluation process starts. Having a flag in EvalCallback to set the seed if you want or with a default value keeping the same behavior as it is now should meet requirements for both cases.
