### ISSUE TITLE
recurrent policy implementation in ppo [feature-request]

### ISSUE THREAD

**Issue by pushkalkatara** [DLR-RM/stable-baselines3#18]
Hi, is CNNLSTM based policy implementation anytime soon for ppo?

**Comment by araffin** [comment]
Hello,
Please take a look at the roadmap: #1 

It is planned but for v1.1+ (so not before 1 or 2 months at least). In the meantime, you can always use frame-stacking if you need to account for history (it yields most of the time competitive results).

This feature will need extra care because it may complexify the codebase, it is a feature wanted by users and it is also an open research question.

**Comment by zhihanyang2022** [comment]
@pushkalkatara Having worked on getting recurrent networks to work with DDPG, TD3 and SAC (https://arxiv.org/pdf/2110.12628.pdf), one important question is, do we want to apply recurrent to take into account of the (1) entire history or (2) just a short window of it? As arrafin mentioned, if your problem is (2), then stacking would be an easier option. In fact, there isn't a simple solution that allow both (1) and (2) to be implemented together.

**Comment by araffin** [comment]
I have a very experimental version of recurrent PPO in a SB3 contrib branch based on SB2/cleanRL implementation: https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/compare/feat/ppo-lstm

Use it at your own risk :p 
(I will try to continue to work on it but help is welcome too)
