### ISSUE TITLE
[Question] Wired behavior with SubprocVecEnv

### ISSUE THREAD

**Issue by Yanzhou-Jin** [DLR-RM/stable-baselines3#1822]
### ❓ Question

Hi, 

We ran into a problem with the SubprocVecEnv. While we are using this multi-processing feature for MuJoCo-based environment, with num_cpu being set to 100 in a workstation of 20 cpus, the CPU usage remains very low during the interaction with MuJoCo, below 40%, which we thought should be very high as MuJoCo is a cpu-based physical engine and the RAM usage is around 60%. I'm wondering if this is the case we should be expecting and is there a way to better utilize the CPUs?

Based on the documentation where it suggests _"For performance reasons, if your environment is not IO bound, the number of environments should not exceed the number of logical cores on your CPU"_, we also tried to set the num_cpu to 20, and the cpu usage is even lower, below 20%.

```
num_cpu = 100
vec_env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])
vec_env = VecNormalize(vec_env, norm_obs=True, norm_reward=True, clip_obs=10.)
model = TD3("MultiInputPolicy", vec_env, verbose=1, train_freq=1)
model.learn(total_time_steps)
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> While we are using this multi-processing feature for MuJoCo-based environment, with num_cpu being set to 100 in a workstation of 20 cpus, the CPU usage remains very low during the interaction with MuJoCo, below 40%, 

Probably because the bottleneck is the gradient update, not the data collection, on the GPU usually.
For this kind of task, you should probably have a look at SBX: https://github.com/araffin/sbx (up to 20x faster than SB3, but it supports a subset of what SB3 can do).

> I'm wondering if this is the case we should be expecting and is there a way to better utilize the CPUs?

You can try different things:
- use a `DummyVecEnv` (as suggested in the doc)
- change the algorithm to PPO/A2C that have much faster gradient update (you need to update the `n_steps` because `batch_size = n_steps * n_envs`) and make everything run on CPU only (PPO is usually faster on CPU only unless you are using CNN)
- play with the `OMP_NUM_THREADS` env variable
