### ISSUE TITLE
[Question] Logging with different x-axis values

### ISSUE THREAD

**Issue by npit** [DLR-RM/stable-baselines3#1835]
### ❓ Question

Say we want to log values to  tensorboard with an x axis different than the current timestep (e.g., global episode count) and use `self.logger.dump` where we want. Should we create a different logger object for our callback, given other values may be accumulated in the logger (e.g. train metrics)? 

What do you recommend?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
it sound more like a tensorboard question...
You have different options.
One is to use `Monitor` files and add information there (saved per episode), you can then load and plot this info per timesteps, per episode or per wallclock time, that's what we do in the RL Zoo:  https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/rl_zoo3/plots/plot_train.py

Otherwise, I haven't tried logging things with another axis to tensorboard (I'm mostly using W&B and monitor files), so it might work too.
