### ISSUE TITLE
[Question] About the logger

### ISSUE THREAD

**Issue by XiaobenLi00** [DLR-RM/stable-baselines3#1997]
### ❓ Question

In the doc https://stable-baselines3.readthedocs.io/en/master/common/logger.html, there is a warning
<img width="723" alt="image" src="https://github.com/user-attachments/assets/bad3892f-ac7e-4d91-bbfd-2c8c7ffa4c55">
I am wondering that if I a custom logger object like
```python
logger = configure(f'results_{job_data.env}')
model = PPO(job_data.policy, env,  verbose=1,
                    tensorboard_log=f"wandb/{run.id}",
                    learning_rate=job_data.learning_rate, 
                    batch_size=job_data.batch_size, 
                    policy_kwargs=policy_kwargs,
                    gamma=job_data.gamma, **job_data.alg_hyper_params)
...
model.set_logger(logger)
model.learn(
    total_timesteps=config["total_timesteps"],
    callback=callback,
)
```

How should I set `tensorboard_log` and `verbose`? Because I notice that in the code below, the settings is overwritten and no info is logged.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
why do you need a custom logger in your case? it seems that you just want to change the name, we have `tb_log_name` parameter (to the `learn()` method) for that.

Nothing is logged in your case because you didn't specify any logger format...
https://github.com/DLR-RM/stable-baselines3/blob/9a3b28bb9f24a1646479500fb23be55ba652a30d/stable_baselines3/common/logger.py#L638

the built-in configure is here: https://github.com/DLR-RM/stable-baselines3/blob/9a3b28bb9f24a1646479500fb23be55ba652a30d/stable_baselines3/common/utils.py#L181-L215
