### ISSUE TITLE
[Question] TD3 algorithm， During training，why limit the next_actions

### ISSUE THREAD

**Issue by Danny551** [DLR-RM/stable-baselines3#2022]
### ❓ Question

TD3 algorithm， During training，why limit the next_actions？
If my action range is much larger than [-1,1], the data is truncated
https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/td3/td3.py#L171

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

you can find some answers here why the action space should be normalized: https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#tips-and-tricks-when-creating-a-custom-environment 

For this piece of code: https://github.com/DLR-RM/stable-baselines3/blob/3d59b5c86b0d8d61ee4a68cb2ae8743fd178670b/stable_baselines3/td3/td3.py#L171
it is because we assume the action is normalized (https://github.com/DLR-RM/stable-baselines3/blob/3d59b5c86b0d8d61ee4a68cb2ae8743fd178670b/stable_baselines3/common/off_policy_algorithm.py#L400-L402)
and also because the default hyperparameters are tuned for a normalized action space, centered around zero.
