### ISSUE TITLE
[Question] Can a model be used in environments with different observation_space sizes?

### ISSUE THREAD

**Issue by SummerDiver** [DLR-RM/stable-baselines3#2031]
### ❓ Question

I am trying to use stablebaselines3 to handle a graph-related problem. Graphs of different sizes will have different numbers of nodes and edges, resulting in different observation space sizes of the environment defined based on this.

My goal is to train an agent using environment A and then use it in environment B. I have customized a feature extractor using a graph neural network and it should be able to handle inputs of graphs of uncertain sizes.

However, when I try to input the observation generated by environment B into the model, an error occurs:

```python
    env_small = GymMISEnv(data_folder_path) # with observation shape (148640, 2)
    env_big = GymMISEnv(test_data_folder_path) # with observation shape (250151, 2)
    policy_kwargs = {
        "features_extractor_class": GNNFeatureExtractor,
        "features_extractor_kwargs": {"features_dim": 64},
        "net_arch": dict(pi=[128, 64], vf=[128, 64]),
    }
    model = PPO("MultiInputPolicy", env_small, policy_kwargs=policy_kwargs, verbose=1) # env_small to train
    obs, _ = env_big.reset() # switch to env_big
    model.predict(obs)  # Error: Unexpected observation shape (250151, 2) for Box environment, please use (148640, 2) or (n_env, 148640, 2) for the observation shape.
```

Is there a way to handle this problem?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
there is no "out of the box" solution for your problem, you will probably need to add an adapter layer to have the same size at the end (and also the model might complain, we have some checks at load time).

**Comment by araffin** [comment]
> I've tried this and seems it's worked. However, when it comes to saving and loading, I have to:

looks fine, `model.policy` is just a pytorch module and can be saved/loaded on its own (https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#id3)

> ound that the old sb seems has this feature(https://github.com/hill-a/stable-baselines/pull/344), does sb3 also support this?

https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#accessing-and-modifying-model-parameters

**Comment by romeshprasad** [comment]
Hi. 
I am working on a similar type of graph problem in stable baseline 3, where i am looking to scale the model by training on A which is a small env and testing it on B which is a big env. 

Where you able to arrive to the solution? 
One hack I found was changing the initialization of the observation space of small env to a very high number. Then before step and reset make sure you pad the rest of the empty spaces in your observation space as zero. It works because then both the model has same shape. But I don't like this idea because there will be a point in future where the model's observation space will go beyond what I have defined in my small env. 

Did you find an alternative way of doing this?

> Hi there, it comes to me that since the policy network actually has the same structure for both env_small and env_big, does it make any sense if I create model_A using env_small and model_B using env_big, and then;

In this idea do you train the model both on A and B? or do you just used the trained model_A and test on model_B?

**Comment by romeshprasad** [comment]
Your idea works!!! Thank you. Glad, Now I don't have to fix my observation space during initialization.
