### ISSUE TITLE
[Enhancement] Use PyTorch's native TanhTransform?

### ISSUE THREAD

**Issue by ManifoldFR** [DLR-RM/stable-baselines3#207]
**Describe the bug**

As noted in https://github.com/DLR-RM/stable-baselines3/issues/36#issuecomment-634729158, the current `common.distributions.TanhBijector` used to squash actions in SAC (for instance) can be replaced by PyTorch's native transform.

We can redefine `SquashedGaussianDistribution` by subclassing `torch.distributions.TransformedDistribution` as in the PyTorch docs [for how the Weibull distribution is defined](https://pytorch.org/docs/stable/_modules/torch/distributions/weibull.html#Weibull). This will automatically define the methods to sample, compute the sample score, compute the cdf, etc with the right transforms/corrections.

The same design pattern could be used later when using other transforms.

If this is a good idea, I'll go ahead and make a PR.

**Comment by araffin** [comment]
Hello,
Thanks for the suggestion, this was introduced in https://github.com/pytorch/pytorch/pull/19785, so we need to check which PyTorch version is needed (hopefully 1.4 is enough).
I would like also to make use of `Independent` instead of reshaping the entropy and `log_prob` at different places.

However, we need to be extra careful when doing such change. For instance, they have a different implementation for the inverse: https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/distributions.py#L641
vs
https://github.com/pytorch/pytorch/pull/19785/files#diff-9c38272c807be20a5832ca58bc3b1f3454c70d30e28ecbd39ca40191219f7d81R410

**Comment by ManifoldFR** [comment]
Unfortunately, `TanhTransform` was only added at the 1.5 release: https://github.com/pytorch/pytorch/releases/tag/v1.5.0. This change would break BC with PyTorch 1.4, then, unless we perform a check for `torch.__version__` in the code...

For the instability, it seems the docstring suggets using `cache_size=1`. Hopefully this would be enough to not break this.
