### ISSUE TITLE
Running PPO on multiple GPU's.

### ISSUE THREAD

**Issue by pouyajafarian** [DLR-RM/stable-baselines3#264]
Hello,

I would like to run the PPO algorithm [https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html](link) on a Google Cloud VM distributed on multiple GPU's. Looking at the documentation I can find below text:

`...creating a multiprocess vectorized wrapper for multiple environments, distributing each environment to its own process, allowing significant speed up when the environment is computationally complex.`

Does this mean using the vectorized wrapper I should be able to run on multiple GPU's? 

Thanks for your help!

**Comment by Miffyli** [comment]
Hey. 

Depends on what you want to parallelize. If you want to parallelize the algorithm updates itself, then no, there is no support for multi-gpu setup right now. Vectorized environments _only_ parallelize environments. If you have compute-heavy environments running them in parallel might speed up gathering samples, but does not affect algorithm training itself.

**Comment by araffin** [comment]
>Does this mean using the vectorized wrapper I should be able to run on multiple GPU's?

PPO is quite lightweight, so unless you are using a big network for the policy/value network, I would recommend you to get better cpus rather than more gpu. The bottleneck usually comes from the environment simulation not the gradient update.

Please take a look at the issue checklist next time as it appears to be a duplicate ;)


Related issues:

- https://github.com/hill-a/stable-baselines/issues/308#issuecomment-489546650
- https://github.com/araffin/rl-baselines-zoo/issues/83
- https://github.com/araffin/rl-baselines-zoo/issues/72
- https://github.com/DLR-RM/stable-baselines3/issues/75
- https://github.com/hill-a/stable-baselines/issues/911#issuecomment-650756363

**Comment by araffin** [comment]
> . I tried to set device=cuda:1 but I found that the task is still deployed at the default cuda:0. Thanks!

could you please open an issue with a minimal code to reproduce? (this seems to be a bug)
Can you try with `device=torch.device("cuda:1")`?

as a quick fix, you can play with `CUDA_VISIBLE_DEVICES` env variable to mask the other GPUs.
