### ISSUE TITLE
[Question] Using tensorboard with custom Gym environment

### ISSUE THREAD

**Issue by halvorot** [DLR-RM/stable-baselines3#309]
### Question

I am using a custom Gym environment and training a PPO agent on it. Using the documentation I have managed to somewhat integrate Tensorboard and view some graphs. The problem is that some desired values are missing (like reward graph). I am using the make_vec_env function that as I understand will wrap the environment in a Monitor class. How do i get more control over what is reported, or at least add values.

I have looked at the following without any luck. When I use a custom callback class (that inherits from BaseCallback) it suddenly does not report anything but fps to tensorboard: 
https://stable-baselines3.readthedocs.io/en/master/guide/tensorboard.html#logging-more-values

Any input on how to have more control over the tensorboard reporting would be greatly appreciated.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by tfederico** [comment]
I am interested as well, I am trying to log some "sub-rewards" using Tensorboard at training time, but I can't seems to figure out how to access the values using `self.training_env` inherited from `BaseCallback`. How do I synchronize the vectorized envs in `self.training_env.venv.env` to obtain a single environment?

**Comment by araffin** [comment]
>The problem is that some desired values are missing (like reward graph).

you mean that the training reward is not showing in tensorboard?
is it showing at least in the terminal?
did you try with a regular env?
usually it is because a Monitor wrapper is missing...

what version of SB3 are you using?
could you try upgrading to master version? (cf. doc)

>How do i get more control over what is reported, or at least add values.

this is normally covered by the documentation

>it suddenly does not report anything but fps to tensorboard:

could you write a minimal working example (without custom env) to reproduce the bug?

>Any input on how to have more control over the tensorboard reporting would be greatly appreciated.

maybe related: https://github.com/DLR-RM/stable-baselines3/issues/286

> I am trying to log some "sub-rewards" using Tensorboard at training time,

you sould take a look at `self.locals`, you should be able to access the reward there.

**Comment by halvorot** [comment]
Thank you for the quick reply. 

It seems that it now reports the reward in rollout/ep_rew_mean. This was not present in neither the terminal or tensorboard before. I don't know how I got it working, but it is.

I am now using just a simple callback function (def callback(_locals, _globals):...) that does not do any reporting to tensorboard. I will try with the custom callback class and add other variables to tensorboard at some later point.

**Comment by halvorot** [comment]
However I am noticing that the rollout "tab" does not appear every time. Is there a specific criteria that has to be met to get this logged?

**Comment by araffin** [comment]
>I am now using just a simple callback function (def callback(_locals, _globals):...) that does not do any reporting to tensorboard. I will try with the custom callback class and add other variables to tensorboard at some later point.

Please use custom classes, custom callback functions are deprecated (in fact they are not mentioned anymore in the doc).

>However I am noticing that the rollout "tab" does not appear every time. Is there a specific criteria that has to be met to get this logged?

if you don't provide any minimal working example, it is hard to say.
I would assume you are using PPO, so the condition is here: https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/on_policy_algorithm.py#L239
and the update is done here: https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/base_class.py#L398

**Comment by axkoenig** [comment]
Hi everyone,

I know this issue is closed but I thought it might be helpful to leave this example of using a TensorboardCallback with a custom environment here. I am logging the cumulative "sub-rewards" of one rollout to Tensorboard in the following way.


```python 
class TensorboardCallback(BaseCallback):
    def __init__(self, verbose=1):
        super(TensorboardCallback, self).__init__(verbose)
        self.cum_rew_1 = 0
        self.cum_rew_2 = 0

    def _on_rollout_end(self) -> None:
        self.logger.record("rollout/cum_rew_1", self.cum_rew_1)
        self.logger.record("rollout/cum_rew_2", self.cum_rew_2)

        # reset vars once recorded
        self.cum_rew_1 = 0
        self.cum_rew_2 = 0
    
    def _on_step(self) -> bool:
        self.cum_rew_1 += self.training_env.get_attr("reward_1")[0]
        self.cum_rew_2 += self.training_env.get_attr("reward_2")[0]
        return True


class MyEnv(gym.Env):
    def __init__(self):
        ... 

    def step(self, action):
        ...
        # sub-rewards
        self.reward_1 = np.random.random()
        self.reward_2 = np.random.random()
        weight_2 = 5

        # total reward
        reward = self.reward_1 + weight_2 * self.reward_2
        ...
        return obs, reward, done, logs


def main(args):
    ...
    env = MyEnv()
    n_actions = env.action_space.shape[-1]
    action_noise = NormalActionNoise(mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions))
    model = TD3(MlpPolicy, env, action_noise=action_noise, verbose=1, tensorboard_log=log_path)

    rewards_callback = TensorboardCallback()
    model.learn(total_timesteps=args.time_steps, tb_log_name=args.log_name, callback=rewards_callback)
    ...
```
The important part is that from your callback you can get any local variable within your environment object with `self.training_env.get_attr("attribute")[0]`. There is a similar method to set the attributes. Please comment if you have any suggestions! :-)

**Comment by Miffyli** [comment]
@axkoenig 

I might have missed something crucial, but what happens if you do simply `self.training_env.reward_1`? This trickery with `get_attr` _should_ do that exact same thing, but I might have missed an important here. If this is something that is always (or almost always) required to access desired things, it might be a good thing to tell about in docs.

**Comment by axkoenig** [comment]
Hi @Miffyli, 

yeah I tried this, but it throws an ```AttributeError: 'DummyVecEnv' object has no attribute 'reward_1'```. 
Yes, I also found the `TensorboardCallback` a little poorly documented, to be honest. Should we update the docs on this, @araffin?

**Comment by Miffyli** [comment]
Hmm hmm I find it odd that `get_attr` works, but thanks for the information!

And yes, any updates that make docs more clear for users are always welcome :)

**Comment by araffin** [comment]
>Please comment if you have any suggestions! :-)

the info dict of the environment is made for such practice, and in the callback you will only need to call `self.locals["infos"]` (and then access the right key).

> Yes, I also found the TensorboardCallback a little poorly documented, to be honest. Should we update the docs on this, @araffin?

What would you like to add?
(in general, I'm always for improving the documentation, I just need to know what you want to do ;))

**Comment by axkoenig** [comment]
Mh, strange when I call the `self.locals["infos"]` dict inside of `_on_step` of the `TensorboardCallback` it is empty. Will I need to fill it manually inside of my custom environment?
> What would you like to add?
> (in general, I'm always for improving the documentation, I just

I would add a simple example of how to use the `TensorboardCallback` in combination with a custom environment: In the `_on_step` method [here](https://github.com/DLR-RM/stable-baselines3/blob/master/docs/guide/tensorboard.rst#logging-more-values) we could show how to access a variable of the environment rather than creating a random variable with `value = np.random.random() `

**Comment by araffin** [comment]
>Mh, strange when I call the self.locals["infos"] dict inside of _on_step of the TensorboardCallback it is empty. Will I need to fill it manually inside of my custom environment?

of course, how would it do it otherwise ;) ? (or how would the info dict records magically what you want?)

>I would add a simple example of how to use the TensorboardCallback in combination with a custom environment: In the _on_step method here we could show how to access a variable of the environment rather than creating a random variable with value = np.random.random() 

alright, then please go ahead ;)
