### ISSUE TITLE
[Feature Request] Log actual return, and not only mean return

### ISSUE THREAD

**Issue by LucasAlegre** [DLR-RM/stable-baselines3#313]
### Motivation

When you use Monitor, it is logged (on tensorboard and on terminal) the mean return considering the last 100 episodes. 
This happens because self.ep_info_buffer is instantiated as a deque(maxlen=100) on BaseAlgorithm class, and on "_dump_logs" method it is logged the mean of the values in this buffer.
I think it is more "natural" to log the actual episode return (total sum of rewards on this specific episode), which is what is commonly reported on papers.

### Pitch

Log the return (total episode reward) every time an episode ends.

### Alternatives

This can be done simply by adding the line below to the method "_dump_logs()" of the class OffPolicyAlgorithm:

```
 if len(self.ep_info_buffer) > 0 and len(self.ep_info_buffer[0]) > 0:
      logger.record("rollout/return", self.ep_info_buffer[-1]["r"])  # ADD THIS LINE
      logger.record("rollout/ep_rew_mean", safe_mean([ep_info["r"] for ep_info in self.ep_info_buffer]))
      logger.record("rollout/ep_len_mean", safe_mean([ep_info["l"] for ep_info in self.ep_info_buffer]))
```

### Additional context

rollout/ep_rew_mean vs actual return (created by me using the modification above).

![image](https://user-images.githubusercontent.com/20215161/107160853-95c9ff00-6977-11eb-99cc-c35e3ff606d2.png)

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
Please fill in the issue template completely ;) (including proposed solution and alternatives)

>I think it is more "natural" to log the actual episode return, which is what is commonly reported on papers.

I'm not sure what you mean by "actual return"

**Comment by LucasAlegre** [comment]
Hi, now I think I made it clearer! :) Thanks!

**Comment by araffin** [comment]
>`logger.record("rollout/return", self.ep_info_buffer[-1]["r"]) `

This look like it can be easily done with a callback, no ;) ?
Cf doc: https://stable-baselines3.readthedocs.io/en/master/guide/tensorboard.html#logging-more-values
and https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html

**Comment by LucasAlegre** [comment]
Yes, I agree that it is easy to do it with a callback, in fact I already log other metrics with callbacks. 
However, in my opinion, this should be logged by default, because the goal of RL is to maximize return, and it is what someone would most probably report on a paper. At first I thought this is what rollout/ep_rew_mean was logging.
Another option (maybe better) it would be to enable to change the size of the buffer. So we could log the mean of last X steps, and could also set X=1.

**Comment by araffin** [comment]
> because the goal of RL is to maximize return, and it is what someone would most probably report on a paper. 

I would disagree with that statement.
First, most of the time, as mentioned in the [documentation](https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html) you should not report the training reward but use a separate environment for periodic evaluation (and deterministic actions, except for Atari games), this is what the `EvalCallback` is meant for (included in the [rl zoo](https://github.com/DLR-RM/rl-baselines3-zoo), together with plotting script, see [reproducing results](https://stable-baselines3.readthedocs.io/en/master/modules/sac.html#how-to-replicate-the-results)).
Then, in papers, when training reward is reported, it is usually done using a smoothing window otherwise it is too noisy to be readable. Also, if you want to report the episode return with different windows (or no smoothing window at all) , we save the monitor files and have a [plotting script](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/scripts/plot_training_success.py) for that in the zoo too.


>Another option (maybe better) it would be to enable to change the size of the buffer.

this won't work as it will also depends on the log interval...

**Comment by externalsupplierstaff** [comment]
> EDIT: logging last episode reward is easy when working with one env only, it gets tricky with multiple envs.
could you please tell me how to do this with multiple envs?
