### ISSUE TITLE
[Question] How to train "Offline"?

### ISSUE THREAD

**Issue by AdamCuellar** [DLR-RM/stable-baselines3#353]
### Question

What is the best approach to training a model "offline"? Specifically, from what I can tell, A2C makes predictions on each step within the collect_rollouts function; however, I'd like to have it use the states/actions I've saved off. Is the best approach to override the collect_rollouts function?

### Additional context

I'm mostly looking at A2C. I have a simulation that I'd like to load a model into, make predictions over several iterations, save each state/action out, and train on those states/actions with the reward being calculated from the result of the final state. I'd consider this process one timestep and then update/save the model and run the simulation again. I already have a custom environment to run the simulation and parse the states/actions.

### Checklist

- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
I'm not sure what you would like to do exactly.

If you want to train on offline data, you should read more about off-policy algorithms (cf. resources in our doc, especially the spinning up guide) and offline reinforcement learning (you can start with https://arxiv.org/abs/2011.14379, there is also the [d3rlpy](https://github.com/takuseno/d3rlpy) lib for that).

A2C is an on-policy algorithm which means it can update its policy using only transitions generated following its current policy, after which they must be discarded as the policy changed because of the gradient update.

**Comment by AdamCuellar** [comment]
I can also get rewards before the very end; however, due to the closed-loop nature of the simulation program I can’t run the training of the model without running through the entire simulation. My goal was to run the model with its current policy over the entire simulation, train based off its performance saved out as the states/actions/rewards, update the policy, and then run the simulation again.

From what you’re saying though, that sounds like it’s not possible with A2C. I appreciate your help and I’ll look into other off-policy algorithms. If you have any recommendations that are implemented in d3rlpy, please let me know!

**Comment by araffin** [comment]
>I can’t run the training of the model without running through the entire simulation. 

I'm not sure what you mean by "running through the entire simulation", if that mean that it is asynchronous or that you always need to finish one trial before updating the policy, you could modify A2C and its buffer to be episodic (you will need to fork SB3).
Otherwise, we provide `train_freq=(1, "episode")` (train only after one episode, should be used with `gradient_steps=-1`, cf. doc) for off-policy algorithms like DQN/SAC.

**Comment by AdamCuellar** [comment]
Yes that’s what I mean, the simulation is asynchronous and I need to finish one trial before updating the policy. Where is the buffer set for A2C? I will try to modify the code if the off-policy algorithms don’t work as I’d like. Thank you for the clarification!

**Comment by Miffyli** [comment]
@AdamCuellar 

Buffer is created [here](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/on_policy_algorithm.py#L108) (a function which A2C inherits), and samples are added [here](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/on_policy_algorithm.py#L183).
