### ISSUE TITLE
[Question] How to implement parameter noise for PPO

### ISSUE THREAD

**Issue by nico-bohlinger** [DLR-RM/stable-baselines3#368]
I want to add parameter noise to the PPO algorithm but I'm not an expert by any means in regards to the stable-baseline implementation of PPO and pytorch.
Could someone give me a rough idea where in the code I could try to add parameter noise and how (pytorch specific)?
I saw some implementation for DDPG in stable-baselines2, but I think this isn't reimplemented in stabe-baselines3.

**Comment by Miffyli** [comment]
I believe this is what SDE parameters are for. @araffin could you clarify? :)

**Comment by araffin** [comment]
Hello,

>I want to add parameter noise to the PPO algorithm but I'm not an expert by any means in regards to the stable-baseline implementation of PPO and pytorch.

To learn more about the internals of SB3, we have a developer guide (cf. doc).

One important question is why would you need parameter noise?

If this is to try to have better performances, you probably don't need it, and if you are working with continuous actions, I would recommend you to take a look at generalized State-Dependent Exploration (included in SB3).
If you need hyperparameter tuning, it is included in the rl zoo: https://github.com/DLR-RM/rl-baselines3-zoo


Otherwise, best would be probably to take a look at what others have done with SB3: https://github.com/smileyenot983/stable_baselines_modified
