### ISSUE TITLE
[Question] evaluate_policy with render=True not working

### ISSUE THREAD

**Issue by modanesh** [DLR-RM/stable-baselines3#404]
I have this following piece of code:

```python
env = make_vec_env(args.env_name, n_envs=1)
env_dir = os.path.join("./models", args.env_name)
stats_path = os.path.join(env_dir, "vec_normalize.pkl")
model_path = os.path.join(env_dir, "model.pt")
model = PPO.load(model_path)
env = VecNormalize.load(stats_path, env)
env.training = False
env.norm_reward = False
mean_reward, std_reward = evaluate_policy(model, env, render=True)
```

Everything works fine and there are no errors or warnings being printed. However, there are also no rendering which is a bit weird given the fact that I have `render=True` in `evaluate_policy()`.

I am running it on macOS Big Sur (11.2.3) and have the following packages installed:
```
stable_baselines3==1.0
gym==0.17.3
```
Any suggestions?

**Comment by araffin** [comment]
Hello,
which env are you using?

**Comment by modanesh** [comment]
Hi!
I've tested on a few PyBullet environments: AntBulletEnv-v0, HalfCheetahBulletEnv-v0, and HopperBulletEnv-v0.

**Comment by araffin** [comment]
The issue comes from pybullet.

You have two solutions:
- call render before any reset, see https://github.com/DLR-RM/rl-baselines3-zoo/issues/57#issuecomment-763520280 (but you will probably need to had a `time.sleep()` between each step to see something)
- use a `SubprocVecEnv`, this method is the one used in the rl zoo: https://github.com/DLR-RM/rl-baselines3-zoo
