### ISSUE TITLE
[Feature Request] Bringing wandb logging to sb3

### ISSUE THREAD

**Issue by krishpop** [DLR-RM/stable-baselines3#480]
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.
Please post your question on the [RL Discord](https://discord.com/invite/xhfNqQv), [Reddit](https://www.reddit.com/r/reinforcementlearning/) or [Stack Overflow](https://stackoverflow.com/) in that case.

### 🚀 Feature

Bringing wandb logging to sb3

### Motivation

 I have been using [weights and biases](http://wandb.ai/) for a project and added it as an output format to the loggers (in my fork) so that it could be used instead of tensorboard for logging metrics during a run (this includes uploading Video files, Images, histograms, and scalar values as well).

### Pitch

I would like to add wandb as an logger output option (with an optional import given whether or not it is installed).

### Alternatives

n/a

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Related issues #333 and https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/6 , and a comment https://github.com/DLR-RM/stable-baselines3/issues/1

No core support was included originally because of the requirement of wandb requiring online accounts and all that (but has it changed?). In any case, support through callbacks should be easy to add. In case you add this kind of support, we would welcome contributions to the [contrib repo](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/) :)

**Comment by krishpop** [comment]
Thanks for the fast response and quickly finding that related issue/comment! Indeed they still require online accounts, I can just try adding it to the contrib repo instead.

**Comment by araffin** [comment]
Now officially supported: https://docs.wandb.ai/guides/integrations/other/stable-baselines-3
Video: https://www.youtube.com/watch?v=ed1bqaZGOQw
