### ISSUE TITLE
DQN decreasing reward after exploration period

### ISSUE THREAD

**Issue by Arun0013** [DLR-RM/stable-baselines3#498]
Using DQN, I observe that the average reward is decreasing and the loss is increasing after the initial exploration period (i.e., till the exploration rate settles to the final value). Please see the below figure for more details. I tried increasing the exploration_fraction but that did not help. IWhat could be the reason for this behavior? 
<img width="289" alt="Loss" src="https://user-images.githubusercontent.com/26017869/124206320-bfd7b580-db00-11eb-8ec0-cf7f904cdbfc.PNG">
<img width="618" alt="Reward" src="https://user-images.githubusercontent.com/26017869/124206323-c108e280-db00-11eb-88b8-a705731133cc.PNG">

**Comment by Miffyli** [comment]
Please use appropriate issue templates next time.

This could be expected behaviour, depending on what your final exploration rate is. Without exploration might be failing some important (impossible to say without more info on the environment). These issues are not for technical support on custom environments, so I recommend following links [here](https://github.com/DLR-RM/stable-baselines3/blob/master/.github/ISSUE_TEMPLATE/question.md) to ask further questions. If you believe there is a bug, share minimal code to replicate the issue.

**Comment by Arun0013** [comment]
Thanks for the clarity. Will you the appropriate template from next time.
