### ISSUE TITLE
[Question] Why do we normalize the whole transition in the HER sample method instead of just the current observation itself?

### ISSUE THREAD

**Issue by JatGwingLam** [DLR-RM/stable-baselines3#517]
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.
Please post your question on the [RL Discord](https://discord.com/invite/xhfNqQv), [Reddit](https://www.reddit.com/r/reinforcementlearning/) or [Stack Overflow](https://stackoverflow.com/) in that case.

### Question

Hi,

Could anyone explain a bit why in this [line](https://github.com/DLR-RM/stable-baselines3/blob/503425932f5dc59880f854c4f0db3255a3aa8c1e/stable_baselines3/her/her_replay_buffer.py#L369) inputs the whole transition to normalize the current observation while in this [line](https://github.com/DLR-RM/stable-baselines3/blob/503425932f5dc59880f854c4f0db3255a3aa8c1e/stable_baselines3/her/her_replay_buffer.py#L378) just input the next_obesrvation to normalize the next observation?

### Checklist

- [Y] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [Y] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
The answer lies in the code of `VecNormalize`, the keys that are normalized:
https://github.com/DLR-RM/stable-baselines3/blob/ddbe0e93f9fe55152f2354afd058b28e6ccc3345/stable_baselines3/common/vec_env/vec_normalize.py#L45-L48
which takes effect here:
https://github.com/DLR-RM/stable-baselines3/blob/ddbe0e93f9fe55152f2354afd058b28e6ccc3345/stable_baselines3/common/vec_env/vec_normalize.py#L171-L173

>Could anyone explain a bit why in this line inputs the whole transition to normalize the current observation while in this line just input the next_observation to normalize the next observation?

In both cases, the keys that are normalized are only `observation`, `achieved_goal` and `desired_goal`.
(that made me think that I should double check that `transitions["desired_goal"]` is not modified by reference, otherwise, it would be a bug when using normalization)

**Comment by JatGwingLam** [comment]
@araffin 
Hi Araffin,

Great! Thanks for the answer! I should have read it down a bit about the normalization wrapper here.

All the best,
Lam

**Comment by araffin** [comment]
>I guess the reason why you input the transition instead of the current observation is due to the purpose of concise code, though it seems it would be more straightforward if we use the observation in this line, how do you think?

yes, if we wanted to fully correct, we would have to create a dictionary with `observation`, `achieved_goal` and `desired_goal` as keys. In practice, we don't need to do that as the agent and buffer will ignore the other keys.
note that the resulting `observations` is also a dictionary but only the keys from the observation space are normalized.
