### ISSUE TITLE
[Question] Regarding implementation of multi env off-policy algorithm (DQN, Replaybuffer)

### ISSUE THREAD

**Issue by SonSang** [DLR-RM/stable-baselines3#567]
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.
Please post your question on the [RL Discord](https://discord.com/invite/xhfNqQv), [Reddit](https://www.reddit.com/r/reinforcementlearning/) or [Stack Overflow](https://stackoverflow.com/) in that case.

### Question

Hi, I am amending the codebase to support multiple envs for training DQN networks, which are off-policy in nature. We need this feature for compliance with pettingzoo (you can check it [here](https://github.com/PettingZoo-Team/PettingZoo/issues/467)). I have started from (#439), and now it seems to run without problem in Cartpole environment. 

Since I want to make contribution about this issue, I have some questions regarding design of this replaybuffer.

- I saw that size of the replaybuffer equals to the (replaybuffer size param * num_envs), which is undoubtedly larger (if num_envs is larger than 1) than the user's intention. But I am confused if it is your design intention or not. If we want to make the size of replaybuffer to exactly same (or close to) the parameter that user has given, we have to set the size as (replaybuffer size param / num_envs), I think.
- Also as far as I know replaybuffer has this shape : (buffer ID, env ID, obs dim). So I was wondering if it was your intention to store this buffer as 3 dimension, so storing experience from different envs in different place. Maybe we could just store all the information without classifying them by their envs (then shape would be just (buffer ID, obs dim)). This is just my curiosity, I think classifying them would be more interpretable.

And if you don't mind, maybe I could make PR and do further discussion there. [Here](https://github.com/SonSang/stable-baselines3/tree/multienv-dqn) is my working branch.

### Additional context

Add any other context about the question here.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
I will let @araffin do final answers (it was his sketch), but I agree with both of your points: I feel the buffer size should be just the single parameter `replay_size`, not a multiple by `n_envs`. I also agree that the replay buffer should be of shape `(replay_size, ...)`. I feel it is different shape now because of the former setting (replay buffer is three times larger), and this also makes some of the code easier, but also non-intuitive changes.

**Comment by araffin** [comment]
Hello,

>(replaybuffer size param * num_envs), which is undoubtedly larger (if num_envs is larger than 1) than the user's intention. But I am confused if it is your design intention or not

The initial design was to have something similar to what we have for `RolloutBuffer` which would avoid for loops to insert new entries.
Obviously, we would need to resize the buffer to `buffer_size // num_envs` to avoid unintentional effects.

>Also as far as I know replaybuffer has this shape : (buffer ID, env ID, obs dim). So I was wondering if it was your intention to store this buffer as 3 dimension

This was mostly in case we needed the order of the transitions to be kept (when using `optimize_memory_usage` or as it is the case for `RolloutBuffer` when computing n step return).
But if you can avoid for loops (for dict obs too) and use `(buffer ID, obs dim)` then we can switch to that shape for now (we would need to adapt `HerReplayBuffer` too).
This additional shape (due to the env id) causes some weird `[0]` index in the code currently...

Note: we don't need to support `optimize_memory_usage` for `num_envs > 1`, this would add too much complexity I think

**Comment by araffin** [comment]
I updated my current implementation, remove some for loops and added support for dict obs. I will close this issue in favor of https://github.com/DLR-RM/stable-baselines3/issues/179
