### ISSUE TITLE
[Bug] if done == True should not trigger env.reset()

### ISSUE THREAD

**Issue by jfcabreras** [DLR-RM/stable-baselines3#582]
Hi, I was checking and the `env.reset()` should be made only at the begining of an episode but sb3 does it at the begining and at the end, this could create a conflict for some `env.reset()` functions in custom envs.

For instance:
```
episodes_to_train = [0, 1, 2, 3]

def reset(self):
  self.training_episode += 1
```

I'm skiping some details for the code to work but in this case, if you reset the env at the end of an episode (as it is being made in https://github.com/DLR-RM/stable-baselines3/blob/ddbe0e93f9fe55152f2354afd058b28e6ccc3345/docs/guide/quickstart.rst), it will skip the training for episodes 1 and 3.

**Comment by Miffyli** [comment]
The doc is somewhat misleading: the training is only done with the `learn` call, in which episodes are only reset once, so that should be ok.

However the step-loop only resets at the end of the episodes (+ at the creation of the episode), so that seems correct, too. There is no double-resetting going on.

@araffin btw this quickstart guide seems bit misleading (it sounds like you can train an agent with the first step-loop). Should it be clarified or did I misread?

**Comment by jfcabreras** [comment]
@Miffyli , when you say:

> However the step-loop only resets at the end of the episodes (+ at the creation of the episode), so that seems correct, too. There is no double-resetting going on.

I have a question, shouldn't be the `env.reset()` always at the begining of an episode?

**Comment by Miffyli** [comment]
> I have a question, is it needed to reset it at the end of the episodes? shouldn't it only be closed?

If you intend to continue training/playing, then `reset` is enough (but needed) to start a new episode.
