### ISSUE TITLE
[Question] Understanding Seed

### ISSUE THREAD

**Issue by danielstankw** [DLR-RM/stable-baselines3#642]
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.
Please post your question on the [RL Discord](https://discord.com/invite/xhfNqQv), [Reddit](https://www.reddit.com/r/reinforcementlearning/) or [Stack Overflow](https://stackoverflow.com/) in that case.

### Question

I am running learning using PPO on a custom env made in Robosuite. I do not understand how can I set the seed to specific number in order to be able to reproduce results ? 
I have seen different ways of doing so and I am not sure if what I did is correct. 
_Would appreciate some feedback._

### Additional context

    env = Monitor(env, monitor_dir, allow_early_resets=True)
    
    env.seed(42)
    set_random_seed(seed=42)

    model = PPO('MlpPolicy', env, verbose=2, seed=42, tensorboard_log="./learning_log/ppo_tensorboard/")
    model.learn(total_timesteps=10_000, tb_log_name='learning', reset_num_timesteps=True)`

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
you are doing it the right way, normally, you only need to pass a seed to the constructor (it will also seed the env).
If you don't get reproducible results, then the issue most probably come from the env...
You can quickly check that by using `CartPole-v1` or `Pendulum-v0 ` instead of your custom env.

Related issues: https://github.com/DLR-RM/stable-baselines3/issues/557 and https://github.com/DLR-RM/stable-baselines3/issues/369

**Comment by danielstankw** [comment]
Thank you :)
