### ISSUE TITLE
[Bug] Large drop in mean reward using multiprocessing with make_vec_env and SAC

### ISSUE THREAD

**Issue by thiakx** [DLR-RM/stable-baselines3#699]
### 🐛 Bug

Large drop in mean reward using multiprocessing with make_vec_env and SAC

### To Reproduce

See code below (modified from Colab example, using latest SB3)

```python
# Install stable-baselines latest version
!pip install git+https://github.com/DLR-RM/stable-baselines3#egg=stable-baselines3[extra]

import gym
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3 import SAC, PPO
from stable_baselines3.common.evaluation import evaluate_policy
import time

def compare_multi_process(model_choice, env_id, n_timesteps, num_cpu=6, policy_type='MlpPolicy'):

    eval_env = gym.make(env_id) # environment for evaluation
    vec_env = make_vec_env(env_id, n_envs=num_cpu) # num_cpu = number of processes to use

    # Multiprocessed RL Training
    multi_model = model_choice(policy_type, vec_env, verbose=0)
    model_name = type(multi_model).__name__ # save model name as string for print 
    start_time = time.time()
    multi_model.learn(n_timesteps)
    total_time_multi = time.time() - start_time
    print(f"\nTook {total_time_multi:.2f}s for {model_name}_multi - {n_timesteps / total_time_multi:.2f} FPS")

    # Single Process RL Training
    non_multi_model = model_choice(policy_type, env_id, verbose=0)
    start_time = time.time()
    non_multi_model.learn(n_timesteps)
    total_time_single = time.time() - start_time

    print(f"Took {total_time_single:.2f}s for {model_name}_non_multi - {n_timesteps / total_time_single:.2f} FPS")
    print("Multiprocessed training is {:.2f}x faster!".format(total_time_single / total_time_multi))

    # Evaluate the trained agents
    mean_reward, std_reward = evaluate_policy(multi_model, eval_env, n_eval_episodes=10)
    print(f'Mean reward: {model_name}_multi, {mean_reward} +/- {std_reward:.2f}')

    mean_reward, std_reward = evaluate_policy(non_multi_model, eval_env, n_eval_episodes=10)
    print(f'Mean reward: {model_name}_non_multi, {mean_reward} +/- {std_reward:.2f}')

n_timesteps = 10000
env_id = "Pendulum-v0"
# env_id = "MountainCarContinuous-v0"
compare_multi_process(SAC, env_id, n_timesteps)
compare_multi_process(PPO, env_id, n_timesteps)
```

```bash
Traceback 
Took 18.65s for SAC_multi - 536.27 FPS
Took 110.15s for SAC_non_multi - 90.79 FPS
Multiprocessed training is 5.91x faster!
Mean reward: SAC_multi, -1205.6901091783773 +/- 106.64
Mean reward: SAC_non_multi, -190.3052033510613 +/- 55.82

Took 11.11s for PPO_multi - 899.92 FPS
Took 18.54s for PPO_non_multi - 539.47 FPS
Multiprocessed training is 1.67x faster!
Mean reward: PPO_multi, -1111.555600091256 +/- 332.89
Mean reward: PPO_non_multi, -1040.340094899712 +/- 249.71
```

### Expected behavior

We notice a small decrease in mean reward (~10%) for PPO, which is expected. SAC however is a huge decrease in mean reward (600%+). That is quite extreme. I have tested in other envs such as "MountainCarContinuous-v0" with similar results.

### System Info

Colab with GPU. Latest Chrome. 

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Probably similar to https://github.com/DLR-RM/stable-baselines3/pull/654#issuecomment-997366746
the answer is in the doc, see warning in https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#multiprocessing-with-off-policy-algorithms

**Comment by Darklanx** [comment]
> Probably similar to [#654 (comment)](https://github.com/DLR-RM/stable-baselines3/pull/654#issuecomment-997366746) the answer is in the doc, see warning in https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#multiprocessing-with-off-policy-algorithms

Is there a particular reason that increasing `gradient_steps` is suggested? From what I've seen, increasing the `batch_size` with the same ratio probably can also solve the problem in a similar way.

**Comment by araffin** [comment]
> Is there a particular reason that increasing gradient_steps is suggested?

Increasing `gradient_steps` is to match the single env setting where `gradient_steps = n transitions collected in the env` (= `train_freq` where `train_freq=1` by default).

**Comment by pengzhi1998** [comment]
However, when I use PPO, the same situation happens: multiprocessing leads to reward's big drop. Do you have any idea why this happens? @araffin

**Comment by araffin** [comment]
> However, when I use PPO, the same situation happens: multiprocessing leads to reward's big drop. Do you have any idea why this happens? 

You need to adjust `n_steps` in that case (data collected per update = `n_steps * n_envs`). You can read more about wall clock time/sample efficiency trade-off in our tutorial (part 3, multiprocessing): https://github.com/araffin/rl-tutorial-jnrr19#content

**Comment by pengzhi1998** [comment]
Thank you for your reply!
Actually, I have adjusted `n_steps` and made the buffer size to be consistent (2048). But when the number of parallel environments increases, the training performance went worse.

**Comment by pengzhi1998** [comment]
I tried several combinations:

```
1. n_envs = 1, n_steps = 2048
2. n_envs = 1, n_steps = 1024
3. n_envs = 2, n_steps = 1024
4. n_envs = 4, n_steps = 512
```
The first, third, and fourth combinations have the same buffer size. However, the first and second combinations have similar good performances which are much better than the third and fourth combinations.

**Comment by Miffyli** [comment]
Be careful when interpreting the results: with more environments, each environment will get less steps (e.g. n_envs=2 with n_steps=1024 means 512 steps per environment). If your environment's reward increases as more steps is taken, it will appear as if with more envs the learning is slower. I recommend repeating your experiments multiple times (as usual for RL) and training for long enough. PPO generally does not learn reliably unless at least a handful (say, 10) parallel environments.

Beyond that, we are unable to offer more info other than what is in docs. You need to experiment on what works best for your case :)

**Comment by pengzhi1998** [comment]
Thank you! But I'm a little bit confused. If n_envs=2 with n_steps=1024 in your example, doesn't it mean 1024 steps per environment/process and 2048 steps for the buffer?
Besides, as I'm using a created environment but not gym envs, do you think it could be a problem?

**Comment by Miffyli** [comment]
> Thank you! But I'm a little bit confused. If n_envs=2 with n_steps=1024 in your example, doesn't it mean 1024 steps per environment/process and 2048 steps for the buffer?

Gah sorry, I am not sure what I was thinking: you are completely right! `n_steps` controls the number of samples per environment. I must have been thinking some other library 😅 

> Besides, as I'm using a created environment but not gym envs, do you think it could be a problem?

If you mean a custom environment (one you created yourself), that might influence things, yes.

> And actually, I have tried more than 20 times of training. Specifically, every time n_envs is bigger than one, which means I uses the multiprocessing with stable-baselines3 PPO, the performance is much worse.

Hmm now I am not sure if by performance you mean the agent performance or the training speed.

If training speed: try using `DummyVecEnv` instead of `SubProcVecEnv`. If the environment is fast to run, the overhead of processes (used by `SubProcVecEnv`) negates all the benefit. 

If agent performance (mean episode reward): See araffin's link above for some guidance. The reason may be in your custom environment. For example:

- One environment: the agent collects data and trains on the data from same episode or seed of the env. These experiences correlate with how environment behaves -> updated agent does much better after first updates -> good performance. However, in other seeds, it might not work well
- Two or more environments: agent gets data from multiple envs with different dynamics/episodes/seeds, which better represents the global behaviour of your environment (regardless of the seed) but is harder to learn -> learning is slower, but trained agent will do better in different seeds. 

This is just one guess what could be happening :)

**Comment by pengzhi1998** [comment]
Wow, thank you so much for such a precise explanation!!!

Yes, it's a custom env. And I'm still checking what causes the problem. And sorry for the ambiguity of the "performance". Actually, I'm referring to the agent performance. The training speed is actually faster (with multiprocessing, within a specific time duration, training with multi-processes would collect more timesteps of data). However, after specific timesteps of training, single-process training always has a higher avg reward than multi-process training. 

For example, multi-process training takes a shorter time to reach the training of 81960 timesteps, but its reward is much lower than single-process training. And single-process training takes shorter timesteps or even a shorter time to converge to a higher reward. While multi-process training takes a longer time to converge. After the learning process gets stable, the final performance is much worse than single-process training as well. And it doesn't seem to be the problem of seed. Because for single-beam training, a different seed doesn't influence its performance, while the learned policy looks very similar. The created custom env is very much a simple environment and the task is very simple as well. So I'm a little bit confused about the issue.

**Comment by Miffyli** [comment]
Gotcha :). Thanks for the clarifications! 

I sadly do not have further thoughts to share on this, so you need to explore and read on this phenomena yourself. I still think the result is somewhat expected, it just needs some thought on why it would happen. It might be that single-env training is simply better for your unique env, who knows :)

 I do not have time to dig deeper into this so I won't be replying further, but if you find bugs or come up with ideas that could improve SB3, please open up a new issue.

**Comment by pengzhi1998** [comment]
I really appreciate your help! 
Sure, if I could find anything, I'd be happy to leave the issue (though I think it's rather hard, as SB3 is such perfect work!)
