### ISSUE TITLE
Doc is confusing for the class MlpExtractor

### ISSUE THREAD

**Issue by xy9485** [DLR-RM/stable-baselines3#736]
I find it's confusing when reading the doc of the class MlpExtractor and I refer it below.
https://github.com/DLR-RM/stable-baselines3/blob/54bcfa4544315fc920be0944fc380fd75e2f7c4a/stable_baselines3/common/torch_layers.py#L136-L147

In line 138, it says "Constructs an MLP that receives observations as an input and outputs a latent representation for the policy and a value network". However, according to the context of soruce code, it's not the case. I think this MLP should take the output(size of feature_dim) of the previous feature extractor as input. It constructs policy and value networks and they are sharing some shared layers. This is confusing for me to make sure how to use this class.

**Comment by Miffyli** [comment]
You are right: this class (`MlpExtractor`) is used _after_ the features have been extracted (if extraction is applied, otherwise the input is the observations directly). With MlpPolicy classes this class will be the only module in the network, in which case it does the extraction and mapping to pi/v. 

A PR that adjusts this docstring would be welcomed :)
