### ISSUE TITLE
[Bug] HumanOutputFormat aliases keys with same truncated name

### ISSUE THREAD

**Issue by AdamGleave** [DLR-RM/stable-baselines3#750]
### 🐛 Bug

In `HumanOutputFormat.write`, the output to write is constructed via `key2str[self._truncate(key)]`. Different keys with the same prefix can be mapped to the same truncated key, in which case they will silently overwrite each others value. The user will only see one output for all the keys where multiple were expected truncated to the same, and which key's value "wins" could even be non-deterministic if the call to `write()` happens in different orders.

Happy to work on a PR to fix this once we decide what the right behavior should be. 

I lean towards making `max_size` for `self._truncate` configurable, and perhaps just bumping the default `max_size` which is quite small, especially when you start logging things hierarchically: e.g. we ran into this bug with the keys `agent/rollout/ep_{len,rew}_mean` getting aliased.

In the case that there is still aliasing after `max_size`, I lean towards just printing out both -- we could swap out a dict for a multidict to make this work. Or we could throw an error, but that seems a bit aggressive, especially as other output formats will be fine.

Thoughts?

### To Reproduce

Minimal example of error:

```python
from stable_baselines3.common import logger

def main():
    log = logger.configure(format_strings=["stdout"])
    log.record("foo", 42) # correct
    long_prefix = "foobar" * 4
    for i in range(3):
        log.record(long_prefix + str(i), i)
    log.dump()

if __name__ == "__main__":
    main()
```

Produces:
```
$ python sb_logger.py 
--------------------------------
| foo                     | 42 |
| foobarfoobarfoobarfo... | 2  |
--------------------------------
```

### Expected behavior

```
$ python sb_logger.py 
--------------------------------
| foo                     | 42 |
| foobarfoobarfoobarfo... | 1  |
| foobarfoobarfoobarfo... | 2  |
| foobarfoobarfoobarfo... | 3  |
--------------------------------
```

### System Info

Bug is present on master, 54bcfa4544315fc920be0944fc380fd75e2f7c4a

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [X] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Miffyli** [comment]
I agree with making `max_size` configurable, otherwise people have to stick with C-esque, every-character-counts type of logging like you described :). 

I think the easiest and most robust solution would be to throw an error if keys get overwritten. This is easy to check for and is transparent on the user what is happening. A proper exception is better than a warning to avoid situations where one trains for long, only to realize some logged value is missing :). (Granted, they should use csv and other formats for this...).

I am not sure of the benefit for printing out all values by using multidict. They still share the same name, and since ordering can not be trusted, it sounds like it is not very useful (and again, prone to situations where data is silently aliased).
