### ISSUE TITLE
[Feature Request] Deprecating env checker in favor of Gym's

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/stable-baselines3#813]
Right now, Gym has an API compliance checker that's a strict superset of the one in SB3 (the code was based on yours), that we're maintaining with newer Gym versions. This should be deprecated and then removed in favor of Gym's to reduce code duplication and because having Gym be in charge of it makes much more sense. How would you guys like to do this?

**Comment by araffin** [comment]
Hello,
as written in https://github.com/DLR-RM/stable-baselines3/issues/525, we will keep it as it contains SB3 specific warnings and checks that the env will specifically work with SB3 algorithms.
SB3 supports less features than Gym allows the user to build, so an env can be valid from Gym point of view but won't work with SB3.

**Comment by araffin** [comment]
> Shouldn't the SB3 env checker apply gym's tests and then additionally apply the SB3 specific tests then?

In theory yes (in fact, nothing prevents the user from calling both checkers), in practice, there might be incompatible tests (for instance https://github.com/openai/gym/blob/master/gym/utils/env_checker.py#L326, gym env checker would fail but the env works with SB3) and code duplication anyway...
I also don't want to spend my time monitoring gym changes. For instance currently I know what is checked by SB3 env checker but I don't know what gym env checker kept/changed since it was merged and that may change again in the future...

**Comment by jkterry1** [comment]
What about having the documentation for yours refer to ours and explaining the difference between the two?

**Comment by araffin** [comment]
> What about having the documentation for yours refer to ours and explaining the difference between the two?

We can put a link to it, but I couldn't find the gym doc about the env checker... (there is no search box on gym doc).

> explaining the difference between the two?

You mean what I wrote here? That gym env checker is for gym and SB3 env checker is for gym+SB3? (not the difference in detail, because this mean I would need to monitor every gym change to its env checker).
