### ISSUE TITLE
[Question] Refactoring/removing the "policy registry"

### ISSUE THREAD

**Issue by Gregwar** [DLR-RM/stable-baselines3#841]
### Question

The policy registry is, in my opinion, confusing to understand the codebase and doesn't solve complex problems. I suggest each algorithm simply declare its own aliases in-class instead (I will attach a PR to this)

### Additional context

Related issue: #88 

### Checklist

- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
>  I suggest each algorithm simply declare its own aliases in-class instead (I will attach a PR to this)

How would you define additional custom aliases?

**Comment by Gregwar** [comment]
The possibility has indeed to be debated (https://github.com/DLR-RM/stable-baselines3/issues/88#issuecomment-653237526 suggested that there is no such use case)

Another way would be to make the dict a static attribute of the algorithm class, so that it could be read and/or changed with something like:

```python
A2C.policy_aliases["MyCustomPolicy"] = MyCustomPolicy
```

I agree that this is different with the "base class" approach.

More formally, my reasons are:
* Iterating over `BasePolicy.__subclasses__()` is a weird pattern: what will happen if I have more complex inheritances on policies?
* Both PPO and A2C `policies.py`, we are registering the same thing, but this is not something we can change at one place without changing it at another place (so it should either be done somewhere else or in another way)

**Comment by araffin** [comment]
> Iterating over BasePolicy.__subclasses__() is a weird pattern: what will happen if I have more complex inheritances on policies?

I do agree for that.

@Miffyli @ernestum @hill-a @AdamGleave  do you have any comments on that feature request?
I had indeed issues in the past because of that. (and I need to check but we may be able to remove `base_policy_class`, unless it is used in a check later on, which I hope is the case ;))

**Comment by Miffyli** [comment]
I 100% agree with the point: it indeed is overly complex for what it is doing (I am still trying to figure out why we coded it the way it is 😅 ). Something like the proposed aliases makes much more sense and does not take half a mug of coffee to understand.

**Comment by Gregwar** [comment]
Are you ok with using a static attributes instead of the current proposal ?

**Comment by araffin** [comment]
> Are you ok with using a static attributes instead of the current proposal ?

what would be the cleanest solution according to you?

**Comment by Gregwar** [comment]
I think the static attribute is more versatile since it also allow accessing the policy aliases from the outside (you could know what is the `A2C`'s `MlpPolicy` by writing `A2C.policy_aliases["MlpPolicy"]` and you could change or define your own aliases if needed)

**Comment by AdamGleave** [comment]
Agree that iterating over `__subclasses__` is a strange pattern. I guess the logic was to ensure it is subclassing something like `OnlinePolicy` or `OfflinePolicy` not `BasePolicy` directly, and because we store the policies indexed by the base policy (to handle on vs off-policy algorithms). But if that is the goal perhaps we should have a list of permitted classes-to-subclass instead, as a user could do `class Foo(BasePolicy)`, `class Bar(Foo)` and `register_policy` with `Bar` would  be accepted. If that logic isn't required then https://github.com/DLR-RM/stable-baselines3/blob/52c29dc497fa2eb235d0476b067bed8ac488fe64/stable_baselines3/common/policies.py#L947 could be simplified with just `if isinstance(policy, BasePolicy)`.

On the broader point of if the policy registry is worth it, I lean towards not in the current implementation. Given that each algorithm calls `register_policy`, there's as much duplicated code as @Gregwar's suggestion of algorithm-specific policy aliases. I'm not sure why this is implemented on a per-algorithm basis, though. So I can see two reasonable approaches:
  1. Algorithm-specific aliases. Simple and easy to understand, but a lot of duplicated policy_aliases["MlpPolicy"] = MlpPolicy.
  2. Simplified policy registry. Rather than register_policy automagically guessing the type from base policy, just have a free-form `kind: str` that can right now be e.g. `offline` or `online`. Have the policies themselves (`MlpPolicy`, etc) register policies in the registry. This centralizes it and we could eliminate most of the algorithms `policy.py` files.

Curious to hear others thoughts!

**Comment by Gregwar** [comment]
Just an extra remark, maybe I misunderstood something, but "online" and "offline" are not really examples of kind of policies but kind of algorithms.

"continuous", "discrete", "deterministic", "stochastic" look more like policies properties, which are actually unrelated with the type of associated algorithms. 

My point is that an algorithm being online or offline doesnt provide any type of information on the underlying policy that will be involved, so there is no clear "default" that we will have to override only in some cases. But yes, we could still try to qualify the policy type with a more generic way.

**Comment by AdamGleave** [comment]
Currently [ActorCriticPolicy](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/policies.py#L379) is often registered as "MlpPolicy" (e.g. in [A2C](https://github.com/DLR-RM/stable-baselines3/blob/75b6f3b3b0f207456d9dcac2c6e86e8e2a22115f/stable_baselines3/a2c/policies.py#L14)) for offline RL algorithms whereas e.g. DQN registers [its own "MlpPolicy"](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/dqn/policies.py#L301).

You're right of course that algorithms are offline vs online, not policies, but offline vs online RL algorithms do have broadly consistent needs in the kinds of policies they use. I think `ActorCriticPolicy` works as an `MlpPolicy` for all our currently implemented on-policy algorithms except SAC, for example.

Of course these type aliases could be defined in `OffPolicyAlgorithm` and inherited in subclasses and overridden where needed. I think that would be my preferred solution.

**Comment by Gregwar** [comment]
My current proposal is to make them static attributes in the algorithms, like:

```python
policy_aliases: Dict[str, Type[BasePolicy]] = {
    "MlpPolicy": MlpPolicy,
    "CnnPolicy": CnnPolicy,
    "MultiInputPolicy": MultiInputPolicy,
}
```

In my current PR they are attributes to those classes, but since they don't depend on instance but on classes it can become static members

We can also do like you say, define defaults in `OffPolicyAlgorithm` and `OnPolicyAlgorithm` and re-define when needed

**Comment by araffin** [comment]
> I guess the logic was to ensure it is subclassing something like OnlinePolicy or OfflinePolicy not BasePolicy directly
>  I'm not sure why this is implemented on a per-algorithm basis, though.

Offline/Online is not enough to distinguish cases, because several policy types are algorithm-specific (for instance DQN/TD3/SAC have three different base policies). Defining per algorithm is simple and clear enough in my opinion (and duplicated code is limited).

> I think ActorCriticPolicy works as an MlpPolicy for all our currently implemented on-policy algorithms 

not the case for `RecurrentPPO` or `MaskablePPO` in contrib...

> We can also do like you say, define defaults in OffPolicyAlgorithm and OnPolicyAlgorithm and re-define when needed

I would do that for `OnPolicyAlgorithm` only (see my comment on DQN/TD3/SAC).

**Comment by AdamGleave** [comment]
> I would do that for OnPolicyAlgorithm only (see my comment on DQN/TD3/SAC).

Gotcha, forgot that the offline algos are so heterogeneous, having defaults just for online SGTM.
