### ISSUE TITLE
[Question] Training doesn't benefit from saved model and replay buffer

### ISSUE THREAD

**Issue by XinyuWang2** [DLR-RM/stable-baselines3#868]
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.
Please post your question on the [RL Discord](https://discord.com/invite/xhfNqQv), [Reddit](https://www.reddit.com/r/reinforcementlearning/) or [Stack Overflow](https://stackoverflow.com/) in that case.

### Question

I am using SAC with HerReplayBuffer. Because I usually don't know how many total_timesteps are enough for a task, sometimes the timesteps are not enough. I think I can load a saved model and keep training the model. The training code is basically:
    
    model = SAC(
        "MultiInputPolicy",
        env,
        replay_buffer_class=HerReplayBuffer,
        replay_buffer_kwargs=dict(
            max_episode_length=MAX_EPISODE_STEPS,
        ),
        verbose=1,
    )
    
    model.learn(total_timesteps=TIMESTEPS)
    model.save(model_path)
    model.save_replay_buffer("sac_replay_buffer") 

After that, I do load the model and buffer, then retrain.  The code is:
    
    loaded_model = SAC.load(model_path, env=env)
    loaded_model.load_replay_buffer("sac_replay_buffer")
    model.learn(total_timesteps=int(2e4))

The problem is, based on the training output (like ep_rew_mean), it is more like training from the beginning.  
Can anyone tell me how to fix this? Thank you so much!

Maybe saving checkpoints frequently while training is also a good idea. But I don't find any other ways to do that. So I guess I have to use the above method do this.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Yes, saving checkpoints might be the issue here (the final model might be bad, for some reason). We recommend using [callbacks](https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html#checkpointcallback). 

If that fails, try loading up the model and only evaluating it to see if you get the same results as during training. The initial steps of training after loading _may_ be ruining the already trained parameters. If all that fails, try to include a minimal code to replicate issue (if possible) and at least figures/numbers that show what you are getting :)
