### ISSUE TITLE
How to save and load a trained model?

### ISSUE THREAD

**Issue by mojovski** [DLR-RM/stable-baselines3#928]
Hi, after I learn a model I save it via
```
model.learn(total_timesteps=100000)
model.save("./data/PPO_MultiBinScaling.zip")
```
In another session I load it and apply the model on the same data it has been trained on (test=train) but receive completely different results.
```
model.load("./data/PPO_MultiBinScaling.zip")
```

Also I observed that the results differ between test (on train data) between trials. 

Are there some strange seed somewhere, which make it inconvenient to reproduce the result after learning?

Thank you very much!

**Comment by mojovski** [comment]
Hi @araffin I checked the manual 
https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html#stable_baselines3.ppo.PPO.load
which points me to
https://github.com/DLR-RM/stable-baselines3/issues/597

Using the proposed solution
```
model.learn(total_timesteps=200, log_interval=4, reset_num_timesteps=False)
```
does not help.

**Comment by Miffyli** [comment]
Check #923 for related discussion. There may be many reasons why you are seeing different results than while training. We have tests that ensure that saving and loading the model reproduces the exact behaviour when saved, so I doubt there is an issue there.

**Comment by mojovski** [comment]
Yes, I check it.

However, I guess my problem was that the model.load does not change the object but rather returns the loaded model.
I was assuming that the model object itself is changed.
Using
```model = PPO.load("./data/PPO_MultiBinScalingTrader.zip", env=env)
```
worked.

**Comment by araffin** [comment]
> Yes, I check it.
> 
> However, I guess my problem was that the model.load does not change the object but rather returns the loaded model. I was assuming that the model object itself is changed. Using
> 
> ```
> model = PPO.load("./data/PPO_MultiBinScaling.zip", env=env)
> ```
> 
> worked.

yes, we have a warning about that in the "saving/loading" example in our doc: https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#basic-usage-training-saving-loading

"
load method re-creates the model from scratch and should be called on the Algorithm without instantiating it first, e.g. model = DQN.load("dqn_lunar", env=env) instead of model = DQN(env=env) followed by model.load("dqn_lunar"). The latter will not work as load is not an in-place operation. If you want to load parameters without re-creating the model, e.g. to evaluate the same model with multiple different sets of parameters, consider using set_parameters instead.
"

**Comment by araffin** [comment]
this issue is a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/683 and #533 
Make sure to follow issue checklist next time ;) (notably checking for existing issues).

**Comment by ReHoss** [comment]
I had exactly the same issue! Thanks for the answers!:)
