### ISSUE TITLE
[Bug] Upgrade gym version

### ISSUE THREAD

**Issue by fontanafederico** [DLR-RM/stable-baselines3#990]
Stable baselines require gym==0.21 in setup.py. Since then, there have been breaking changes in Env API ([source](https://github.com/openai/gym/releases)). Are there plans to upgrade gym version and stay compliant with the latest env protocol?

**Comment by araffin** [comment]
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/840 and https://github.com/DLR-RM/stable-baselines3/issues/871

The PR is here: https://github.com/DLR-RM/stable-baselines3/pull/780 (we added instructions in the doc)

PS: do you need special features of gym 0.25 that are not in 0.21?
we are also happy to receive contributions in order to add support to latest gym version (see PR).
